@extends('layouts.default')

@section('content')
<div class="container">
	<div class="row rowsombra">
		<h1 class="text-center">PRIVACY POLICY</h1>
		<p class="text-center">By visiting this Website, you are accepting the policies described in this Privacy Policy</p>
		<br><br>
		<div class="col-sm-10 col-sm-offset-1 margin-bottom-lg">
			<p class="text-justify">International Ravers Charity knows that you care how information about you is used and shared, and we appreciate you trusting that we will do so carefully and sensibly.  Our Privacy Policy is designed to assist you in understanding how we collect and use the personal information you provide to us and to assist you in making informed decisions when using our site and our products and services.  We will not use or share your information with anyone except as described in this Privacy Policy.  This Privacy Policy does not apply to information we collect by other means (including offline) or from other sources.</p><br><br>
			<h2>What Information Do We Collect?</h2>
			<p class="text-justify">When you visit our website or make a donation online, you may provide us with two types of information: personal information you knowingly choose to disclose that is collected on an individual basis and Website use information collected on an aggregate basis as you and others browse our Website.</p><br><br>
			<ol>
			  <li>
			  	<h2>Personal Information You Choose to Provide</h2>
					<ul class="list-unstyled">
					  <li><p class="text-justify">We ask for personal information so that we can fulfill your request and return your message. This information is retained and used in accordance with existing laws, rules, regulations, and other policies. International Ravers Charity does not collect personal information from you unless you provide it to us. If you choose not to provide any of that information, we may not be able to fulfill your request or complete your order, but you will still be free to browse the other sections of the websites owned and administered by International Ravers.org .  This means that you can visit our site without telling us who you are or revealing any personally identifiable information about yourself.</p><br></li>
					  <li><h3>Credit Card Information:</h3><p class="text-justify">International Ravers Charity is grateful for the donations that help us continue our valuable work. It is very important to us that your personal information remains secure. When you donate to InternationalRavers.org, your credit card information is secured by a reputable security company (Comodo Group Inc. ). Also, your credit card number is used only for that particular transaction and is not stored.  You will also notice in your website address bar that the domain name starts with an “https” on those donation pages. This means that information entered on those pages is encrypted for your security. If you have any questions regarding the security of your credit card donation online, please <strong><a href="{{route('contact')}}">contact us</a></strong> or send us an email: SUPPORT@INTERNATIONALRAVERS.ORG</p><br></li>
					  <li><h3>Registration Information</h3><p class="text-justify">You are not required to provide any personal information on our website unless you choose to do so.  We do ask for personal information on our online donation pages to properly enable donation transaction processing. When you donate to Internationalravers.org, you will provide us information about yourself, your firm or company, and your practices when you donate, you may choose register for certain services, or register for email newsletters and alerts.  When you choose to participate in various fundraising or awareness campaigns of InternationalRavers.org, we may request additional information including, but not limited to, your name, an image or photograph, contact information, and narratives authored by you. By choosing to provide any of this information, you are explicitly granting InternationalRavers.org permission to use any provided information for pubic use, posting, and consumption. If you have any questions regarding the security of your registration information, please <strong><a href="{{route('contact')}}">contact us</a></strong> or send us an email:  SUPPORT@INTERNATIONALRAVERS.ORG for more information.</p><br></li>
					  <li><h3>Email Information</h3><p class="text-justify">If you choose to correspond with us through email, we may retain the content of your email messages together with your email address and our responses. Our website does not automatically recognize your e-mail address. We ask for your e-mail address on a number of pages within our site, but you may opt out of e-mail communications at any time by un-checking the box beneath where you entered in your e-mail address, or by clicking the unsubscribe link that is included at the bottom of every e-mail communication from InternationalRavers.org.</p><br></li>
					</ul>
			  </li>
			  <li>
			  	<h2>Website use information</h2>
			  	<ul class="list-unstyled">
			  		<li><p class="text-justify">Anonymous information is collected for every donor and visitor to this site. This includes pages viewed, date and time, and browser type. IP numbers are not stored, but are temporarily used to determine domain type and in some cases, geographic region. We do not make any association between this information and a donor or visitor's identity. our Website utilizes a standard technology called "cookies" (see explanation below, "What Are Cookies?") and Web server logs to collect information about how our Web site is used. Information gathered through cookies and Web server logs may include the date and time of visits, the pages viewed, time spent at our Web site, and the Web sites visited just before and just after our Web site.</p><br></li>
			  		<li><h3>How do we use the information you provide to us.</h3><p class="text-justify">Broadly speaking, we use personal information for purposes of administering and expanding our service and charitable activities, providing donor services and making available other products and services to our donors and prospective donors.  Occasionally, we may also use the information we collect to:</p>
							<ul>
				  			<li>Notify you about important changes to our Website features</li>
				  			<li>Alert you about our new projects or our fulfilled projects</li>
				  			<li>Send you an  invitation to Special events and services</li>
				  			<li>Conduct surveys to measure your satisfaction with our service</li>
				  			<li>Special donation opportunities and offers we think you will find valuable</li>
				  		</ul>
			  		</li>
						<li><h3>What are cookies?</h3><p class="text-justify">A cookie is a very small text document, which often includes an anonymous unique identifier. When you visit a Web site, that site's computer asks your computer for permission to store this file in a part of your hard drive specifically designated for cookies. Each Web site can send its own cookie to your browser if your browser's preferences allow it, but (to protect your privacy) your browser only permits a Web site to access the cookies it has already sent to you, not the cookies sent to you by other sites.</p><br></li>
						<li><h3>How Do We Use Information We Collect from Cookies?</h3><p class="text-justify">As you visit our Web site, the site uses its cookies to differentiate you from other visitors. In some cases, cookies are use to recognize you as a return visitor, or to allow our online community to recognize you as an existing member.  Cookies, in conjunction with our Web server's log files, allow us to calculate the aggregate number of people visiting our Web site and which parts of the site are most popular. This helps us gather feedback in order to constantly improve our Web site and better serve our mission. Cookies do not allow us to gather any personal information about you and we do not generally store any personal information that you provided to us in your cookies.</p><br></li>
						<li><h3>Sharing Information with Third Parties</h3><p class="text-justify">InternationalRavers.org will not sell or trade donor’s information with any organization, nor will InternationalRavers.org send mailings on behalf of other organizations.  You are not required to provide any personal information on our website unless you choose to do so. We do ask for personal information on our online donation pages to properly enable donation transaction processing. We use this information to acknowledge receipt of your donation for tax purposes and may publicly acknowledge your gift on InternationalRavers.org and/or other web services.</p><br></li>
						<li><h3>Legal Disclaimer</h3><p class="text-justify">We may disclosure your personal information if required to do so by law or subpoena or if we believe that such action is necessary to:</p>
							<ul>
				  			<li>(a) Conform to the law or comply with legal process served on us or Affiliated Parties.</li>
				  			<li>(b) Protect and defend our rights and property, the Site, the users of the Site, and/or our Affiliated Parties.</li>
				  			<li>(c) Act under circumstances to protect the safety of users of the Site, us, or third parties.</li>
				  		</ul>
			  		</li>
			  		<li><h3>How Do We Protect Your Information?</h3><p class="text-justify">International Ravers Charity has taken certain physical, administrative and technical steps to safeguard customer information which may include but are not limited To prevent unauthorized access, maintain data accuracy, and ensure the correct use of information. We have put in place appropriate physical, electronic, and managerial procedures to safeguard and secure the information we collect online. Additionally, sensitive data such as credit card numbers are encrypted using SSL and other industry standard measures, to provide an additional level of security.</p><br>
							<ul>
				  			<li><p class="text-justify"><strong>HOW DO WE SECURE INFORMATION TRANSMISSIONS?</strong><br>Email is not recognized as a secure medium of communication. For this reason, we request that you do not send private information to us by email. Some of the information you may enter on our Web site may be transmitted securely via Secure Sockets Layer SSL, 128 bit encryption services, which are enabled by Comodo Group, Inc. <br>Pages utilizing this technology will have URLs that start with HTTPS instead of HTTP.  We cannot, however, ensure or warrant the security of any information you transmit to us or guarantee that your information on the Website may not be accessed, disclosed, altered, or destroyed by breach of any of our physical, technical, or managerial safeguards.  Please <strong><a href="{{route('contact')}}">contact us</a></strong> if you have any questions or concerns.</p></li>
				  			<li><p class="text-justify"><strong>HOW CAN YOU ACCESS AND CORRECT YOUR INFORMATION?</strong><br>You may request access to all your personally identifiable information that we collect online and maintain in our database</p>
									<ul>
										<li><p class="text-justify">CORRECT/UPDATE <br>If you would like to verify the data we have received from you or to make corrections to it, you may <strong><a href="{{route('contact')}}">contact us</a></strong>.</p></li>
										<li><p class="text-justify">CHOICE/OPT-OUT <br>If you have registered to receive communications from us and later change your mind, you may <strong><a href="{{route('contact')}}">contact us</a></strong> to have your name and contact information removed from our distribution lists. You can send an email to: SUPPORT@INTERNATIONALRAVERS.ORG</p></li>
									</ul>
				  			</li>
				  		</ul>
			  		</li>
			  		<li><h3>What About Other Web Sites Linked to Our Web Site?</h3><p class="text-justify">We are not responsible for the practices employed by Web sites linked to or from our Web site nor the information or content contained therein. Often links to other Web sites are provided solely as pointers to information on topics that may be useful to the users of our Web site. <br>Please remember that when you use a link to go from our Web site to another Web site, our Privacy Policy is no longer in effect. Your browsing and interaction on any other Web site, including Web sites which have a link on our Web site, is subject to that Website's own rules and policies. Please read over those rules and policies before proceeding.</p><br>
							<ul>
								<li><p class="text-justify"><strong>YOUR CONSENT</strong><br>By using our Website you consent to our collection and use of your personal information as described in this Privacy Policy. If we change our privacy policies and procedures, we will post those changes on our Website to keep you aware of what information we collect, how we use it and under what circumstances we may disclose it.</p></li>
								<li><p class="text-justify"><strong>CHILDREN'S PRIVACY</strong><br>Protecting the privacy of young children is especially important.  For that reason, we do not knowingly collect or solicit personal information from anyone under the age of 13 or knowingly allow such persons to register. If you are under 13, please do not send any information about yourself to us, including your name, address, telephone number, or email address. No one under age 13 is allowed to provide any personal information to us or our Website. In the event that we learn that we have collected personal information from a child under age 13 without verification of parental consent, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 13, please <strong><a href="{{route('contact')}}">contact us</a></strong>.</p></li>
							</ul>
			  		</li>
			  	</ul>
			  </li>
			  <li><h2>FOR MORE INFORMATION</h2><p class="text-justify">If you have any questions, concerns or comments about your privacy, please send us a description of your concern via email to SUPPORT@INTERNATIONALRAVERS.ORG</p></li>
			</ol>
		</div>
		
	</div>
</div>
@stop